<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>MidiBard.Stage</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DalamudLibPath Condition="'$(DalamudLibPath)' == '' and '$(DALAMUD_HOME)' != ''">$(DALAMUD_HOME)</DalamudLibPath>
    <DalamudLibPath Condition="'$(DalamudLibPath)' == ''">$(APPDATA)\XIVLauncherCN\addon\Hooks\dev\</DalamudLibPath>
    <DalamudLibPath>$([MSBuild]::EnsureTrailingSlash('$(DalamudLibPath)'))</DalamudLibPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Plugin.cs" />
    <ProjectReference Include="..\BardStage.Core\BardStage.Core.csproj" />
    <Reference Include="Dalamud;Dalamud.Bindings.ImGui;Dalamud.Bindings.ImPlot;Dalamud.Bindings.ImGuizmo;HexaGen.Runtime;Lumina;Lumina.Excel;FFXIVClientStructs;InteropGenerator.Runtime">
      <HintPath>$(DalamudLibPath)%(Identity).dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
